likecompetition/likecompetition/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', TemplateView.as_view(template_name='index.html'), name='index'),
	path('posts/', include('posts.urls')),
	path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likecompetition/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
	path('', views.PostListView.as_view(), name='post_list'),
	path('new', views.PostCreateView.as_view(), name='post_create'),
	path('<int:post_id>', views.PostAPIView.as_view(), name='post_api'),
	path('<int:post_id>/detail', views.PostDetailView.as_view(), name='post_detail'),
	path('<int:pk>/edit', views.PostEditView.as_view(), name='post_edit'),
	path('<int:post_id>/comments', views.CommentListCreateView.as_view(), name='comment_list_create'),
	path('comments/<int:comment_id>', views.CommentRetrieveDestroyView.as_view(), name='comment_retrieve_destroy'),
	# path('scrap', views.MyScrapView.as_view(), name='my_scrap'),
	path('<int:post_id>/scrap', views.ScrapToggleView.as_view(), name='scrap_detail'),
    path('sidos', views.SidoListView.as_view(), name='sido_list'),
	path('sidos/<int:sido_id>', views.SigunguListView.as_view(), name='sigungu_list'),
]

likecompetition/likecompetition/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" />
	<link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">
	<title>공가치</title>
	<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
	{% block title %}{% endblock %}
</head>
<body>
	<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<section id="app">
		<h1>공가치</h1>
		<header>
			<div class="hamburger-button" @click="sideBarOpen=!sideBarOpen">☰</div>
			<div class="header-logo"><a href="/">공가치</a></div>
			<nav id="main-menu">
				<ul>
					<li><a href="{% url 'posts:post_create' %}">글쓰기</a></li>
					{% if user.is_authenticated %}
					<li class="profile">
						<span>{{ user.nickname }}<img class="user-image" src="{% static 'images/post_card_user.png' %}"></span>
						<div id="user-menu">
							<ul>
								<li><a href="{% url 'mypage' %}">내 정보</a></li>
								<li><a href="#">스크랩</a></li>
								<li><a href="#">쪽지</a></li>
								<li><a href="{% url 'logout' %}">로그아웃</a></li>
							</ul>
						</div>
					</li>
					{% else %}
					<li><a href="{% url 'signup' %}">회원가입</a></li>
					<li><a href="{% url 'login' %}">로그인</a></li>
					{% endif %}
				</ul>
			</nav>
		</header>
		<div id="container">
			<aside id="side-bar" :class="{ open: sideBarOpen }">
				<ul>
					<li><a href="{% url 'index' %}">홈</a></li>
					<li><a href="{% url 'posts:post_create' %}">글쓰기</a></li>
					{% if user.is_authenticated %}
					<li><a href="{% url 'logout' %}">{{ user.nickname }} / 로그아웃</a></li>
					<li><a href="{% url 'mypage' %}">내 정보</a></li>
					{% else %}
					<li><a href="{% url 'signup' %}">회원가입</a></li>
					<li><a href="{% url 'login' %}">로그인</a></li>
					{% endif %}
				</ul>
			</aside>
			<div id="content">
				<section class="content-main">
					{% block content %}{% endblock %}
				</section>
			</section>
		</div>
	</section>
	{% block end %}{% endblock %}
	<script src="{% static 'base.js' %}"></script>
</body>
</html>